# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza
description: "Hi, Iâ€™m Mammad. I am an AI Engineer with a PhD in Engineering and deep expertise in applied ML, physics-based modeling, and optimization for energy systems. Experienced in leveraging platforms such as LangChain, Langflow, Azure OpenAI, Hugging Face, and OpenAI APIs to develop RAG-enabled copilots, semantic search tools, and intelligent agents. Proficient in prompt engineering, vector search, and agent orchestration, with a strong programming foundation in Python. Passionate about ethical, transparent AI and the responsible advancement of ML in impactful domains, such as clean energy, CCUS, mineral extraction and reservoir simulation. Strong communicator with a record of peer-reviewed publications, stakeholder engagement, and delivering insights to technical and non-technical audiences. Feel free to explore my projects or connect with me using my Linkedin profile link below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mammad-mirza#" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



