# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza
description: "Hi, Iâ€™m Mammad. I am a Data Scientist and Reservoir Engineer with over 10 years of experience in engineering, asset evaluation, and risk-informed decision making within the energy and infrastructure sectors. Experienced in applying statistical modeling, and leading technical risk assessments, evaluating innovative solutions, and fostering cross-functional collaboration to deliver impactful projects aligned with sustainability and climate change goals. Skilled in data analytics, project coordination, with a strong foundation in safety, cost-benefit analysis, and regulatory compliance. Feel free to explore my projects or connect with me using my Linkedin profile link below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mammad-mirza#" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

